info:
  title: "Online Shop API",
  contact: {
    name: "Trần Quang Tuấn",
    url: "https://github.com/vangxitrum",
    email: "tuantq666@gmail.com"
  }
  license: {
    name: "Apache 2.0",
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  },
        "version": "1.0"
paths: {}
swagger: "2.0"
